model: "Jasper"
sample_rate: &sample_rate 16000
labels: &labels [" ", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
         "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "'"]

AudioToTextDataLayer:
    header:
        full_spec: nemo.collections.asr.AudioToTextDataLayer
    init_params:
        sample_rate: *sample_rate
        labels: *labels
        batch_size: 16
        shuffle: true

AudioToMelSpectrogramPreprocessor:
    header: {full_spec: nemo.collections.asr.AudioToMelSpectrogramPreprocessor}
    init_params: {dither: 1e-05, features: 64, n_fft: 512, normalize: per_feature,
      pad_to: 16, stft_conv: true, window: hann, window_size: 0.02, window_stride: 0.01}

SpectrogramAugmentation:
    header: {full_spec: nemo.collections.asr.SpectrogramAugmentation}
    init_params:
        rect_masks: 5
        rect_time: 120
        rect_freq: 50

JasperEncoder:
    header: {full_spec: nemo.collections.asr.JasperEncoder}
    init_params:
      activation: relu
      conv_mask: true
      feat_in: 64
      jasper:
      - dilation: [1]
        dropout: 0.0
        filters: 256
        kernel: [33]
        repeat: 1
        residual: false
        separable: true
        stride: [2]
      - dilation: [1]
        dropout: 0.0
        filters: 256
        kernel: [33]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 256
        kernel: [33]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 256
        kernel: [33]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 256
        kernel: [39]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 256
        kernel: [39]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 256
        kernel: [39]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 512
        kernel: [51]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 512
        kernel: [51]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 512
        kernel: [51]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 512
        kernel: [63]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 512
        kernel: [63]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 512
        kernel: [63]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 512
        kernel: [75]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 512
        kernel: [75]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 512
        kernel: [75]
        repeat: 5
        residual: true
        separable: true
        stride: [1]
      - dilation: [2]
        dropout: 0.0
        filters: 512
        kernel: [87]
        repeat: 1
        residual: false
        separable: true
        stride: [1]
      - dilation: [1]
        dropout: 0.0
        filters: 1024
        kernel: [1]
        repeat: 1
        residual: false
        stride: [1]

JasperDecoderForCTC:
    header:
        full_spec: nemo.collections.asr.JasperDecoderForCTC
    init_params:
        feat_in: 1024
        num_classes: 28
